"""creates new model and updates planet models

Revision ID: fc0fd3f1c57c
Revises: 899e96037f6c
Create Date: 2025-11-04 11:37:10.648497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0fd3f1c57c'
down_revision = '899e96037f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.Float(), nullable=False))
        batch_op.drop_column('moons')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###
